### PR TITLE
Fix minor issues in french translation

### PR DESCRIPTION
**Pull request by adrientoub**
Just installed the extension from the Firefox store and found the "COnsulter" typo a bit annoying so here is my PR to fix it and some other minor issues.

### CODE REVIEW

**Comment by zakius** [comment]
Thanks for your input, I'm not sure about replacing ellipsis with three dots, is there any rule in french to support this change? I can see three dots are used in other languages instead so I'll probably just accept this for consistency.

I checked other changes and while I don't know the language it does seem cleaner and I don't see any issues. There are few yet untranslated strings, if you encounter strings ending with `*` these are falling back to English, ones with `!` at the end are actual keys that lack text in English too. If you encounter any of them feel free to submit pull request to fill these blanks too

**Comment by adrientoub** [comment]
Just changed it to match the other languages but I do not feel strongly about that, can revert the ellipsis change.

I will look for the untranslated strings.

**Comment by zakius** [comment]
Is `corbeille` the go to word to use as `recycle bin` in software? Both seem fitting if I limit myself to translator, but there are known conventions that just seem more appropriate.

According the ellipsis I haven't touched the actual localization files yet since I picked up this project, I'll change triple dots everywhere (unless I'll find some reason not to like language specific punctuation rules)

Once again thanks for your help

**Comment by adrientoub** [comment]
Yes it's the name used on most UIs.

https://fr.wikipedia.org/wiki/Corbeille_(informatique)

**Comment by zakius** [comment]
Okay, thank you

I'll leave this open for a while more to let you update if you find anything else and will pull this in and publish with few other changes sometime next week

**Pull request merged**
